---
title: Stackbit Ampersand Theme
baseurl: "/"
permalink: "/:title/"
layout_style: grid
palette: green
header:
  title: Jerric Lyns John
  logo_img: "/images/jerric-logo.svg"
  has_nav: true
footer:
  content: "&copy; All rights reserved."
  links: []
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
